### ISSUE TITLE
Aalen additive hazard models running too slow on R 3.6.0

### ISSUE THREAD

**Issue by spenafajuri** [scheike/timereg#7]
Dear all,

I'm using timereg to fit an Aalen additive hazard models in a dataset of 55,000 participants of health examination surveys. Fitting a model with 7 variables takes 7 minutes and 35 secs. In an expanded dataset for causal mediation analysis, a similar code has been running for days in a Linux 64GB cluster machine.

Any ideas how I could run the model faster? Or perhaps consider how to optimize the code to speed up the process.

Best wishes,
Sebastián

**Comment by scheike** [comment]
Dear Sebastian,

it is the robust standard errors that take time. If you fit with robust=0 you avoid these.

best
________________________________________

**Comment by spenafajuri** [comment]
Dear Thomas,

Thanks for your suggestion. Without the robust variance estimation, it took less than 10 minutes (the one with robust=TRUE has been running now for 6 days without output)

Best wishes,
Sebastián
